version: '3.8'
services:
  alma-proxy:
    build: ./alma-cors-proxy
    ports:
      - '5555:5555'
    env_file:
      - ./alma-cors-proxy/acp.env
  almafinance-db:
    image: mysql:latest
    restart: always
    env_file:
      - ./env/mysql.env
    ports:
      - '3092:3092'
    volumes:
      - ./almafinance-db.sql:/docker-entrypoint-initdb.d/almafinance-db.sql 
      - almafinance-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
  alma-finance:
    build: ./app
    ports:
      - '5000:5000'
    env_file:
      - ./app/app.env
    volumes:
      - ./app:/app
      - /app/node_modules
      # - /Users/markwarren/Documents/xml:/app/xml
      - /home/almadafis/aeinput:/app/xml
    depends_on:
      almafinance-db:
        condition: service_healthy
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - almafinance-db
volumes:
  almafinance-db: