version: '3.8'
services:
  alma-proxy:
    build: ./alma-cors-proxy
    ports:
      - '5555:5555'
    env_file:
      - ./alma-cors-proxy/acp.env
  alma-finance:
    build: ./app
    ports:
      - '5000:5000'
    env_file:
      - ./app/app.env
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - alma-proxy
